version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_APP_8000
    expose:
      - "8000"
    restart: unless-stopped
    entrypoint: ["python", "-u", "/rp_handler.py", "--rp_serve_api"]
