version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_APPWRITE_8000
    expost:
      - "8000"
    restart: unless-stopped
    entrypoint: ["python", "-u", "/rp_handler.py", "--rp_serve_api"]
